<a href="https://colab.research.google.com/github/GhoneimX7/Deep-Learning/blob/main/NumPy/Python_NumPy_freeCodeCamp_org.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python NumPy Tutorial for Beginners**
[**https://www.youtube.com/watch?v=QUT1VHiLmmI**](https://www.youtube.com/watch?v=QUT1VHiLmmI)

# **importing the library**

In [ ]:
import numpy as np


# **Create/Check numpy array**

In [ ]:
a = np.array([1, 2, 3], dtype= 'int16')
print(a)

[1 2 3]


In [ ]:
b = np.array([[9., 8.0, 7.0], [6.0, 5.0, 4.0]], dtype = 'float16')
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get the Dimension using np.array().ndim
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# Get Shape using np.array().shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# Get type using np.array().dtype
print(a.dtype)
print(b.dtype)

int32
float64


In [ ]:
# Get size using np.array().itemsize >> gets the element size in bytes (1 byte = 8 bits)
print(a.itemsize)
print(b.itemsize)

2
2


In [ ]:
# Get total size using np.array().size >> total number of elements
print(a.size)
print(b.size)

3
6


In [ ]:
# Get total bit size using np.array().nbytes >> total number of bytes = element size in bytes * total number of elemnts
# nbytes = a.itemsize * a.size
print(a.nbytes)
print(b.nbytes)

6
12


# **Accessing/Changing specific elements, rows, columns, etc**

In [ ]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(c)
print(c.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [ ]:
# Get a specific element using np.array()[r, c] >> r for row, c for column
print(c[1, 5])
# Can use the negative indexing too like
print(c[1, -2])

13
13


In [ ]:
# Get a specific row using np.array[r, :]
print(c[1, :])

[ 8  9 10 11 12 13 14]


In [ ]:
# Get a specific column using np.array[:, c]
c[:, 3]

array([ 4, 11])

In [ ]:
# using step size np.array[start_index : end_index : step_size]
c[1, 1:6:2]

array([ 9, 11, 13])

In [ ]:
# rewrite a specific element
c[1, 5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
# select all rows and set the 3rd column to 5
c[:, 2] = 5 
print (c)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [ ]:
# rewrite a specific slice, should be the same shape
c[:, 2] = [1, 2]
print(c)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# 3d example
d = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
d.shape

(2, 2, 2)

In [ ]:
# Get a specific element (works outside in)
d[0, 1, 1]

4

In [ ]:
# Rewrite a slice (should be the same shape)
d[:, 1, :] = [[9, 9], [8, 8]]
print(d)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# **Initializing Different Types of Arrays**

In [ ]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matix
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# any other number 
np.full((2, 2), 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# any other number (full_like(np.array, n))
# any other number (full(np.array().shape, n))
print(np.full_like(c, 4))
print()
print(np.full(c.shape, 6))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]

[[6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]]


In [ ]:
# Random decimal numbers (dose not take a tuple!)
print(np.random.rand(4, 2, 3))
print()
print('#####################')
print()
print(np.random.random_sample(c.shape))

[[[0.99654952 0.59823972 0.06110272]
  [0.78306032 0.59625866 0.95034499]]

 [[0.39529572 0.97752433 0.15883318]
  [0.77639993 0.66442694 0.05577461]]

 [[0.91501935 0.19155593 0.63298948]
  [0.40243801 0.42388412 0.70099156]]

 [[0.37341566 0.94058808 0.38549851]
  [0.52204109 0.04183251 0.10749723]]]

#####################

[[0.96696022 0.67413034 0.36393633 0.18400079 0.24217284 0.1085165
  0.60051578]
 [0.63496012 0.75289197 0.0927487  0.64827281 0.62895614 0.60413766
  0.43076806]]


In [ ]:
# Random Integer numbers  randint(min value, max value, size=(n, m)) "note: max val is exclusive"
print(np.random.randint(7, size=(3, 3)))

[[5 2 2]
 [6 6 3]
 [5 3 3]]


In [ ]:
# Identity matrix (one param)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeating an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
r2 = np.repeat(arr, 3, axis = 1)
print(r1)
print('#########')
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
#########
[[1 1 1 2 2 2 3 3 3]]


In [ ]:
# try to get this matrix with the methods you have learned!
"""
1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1
"""
mat = np.ones((5, 5))
mat[1:4, 1:4] = 0
mat[2, 2] = 9

print(mat)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be careful whe copying arrays!!!**

In [ ]:
# BAD
e = np.array([1, 2, 3])
f = e
print(e)
print(f)
f[0] = 100
print('######')
print(e)
print(f)

[1 2 3]
[1 2 3]
######
[100   2   3]
[100   2   3]


In [ ]:
#Good
e = np.array([1, 2, 3])
f = e.copy()
print(e)
print(f)
f[0] = 100
print('######')
print(e)
print(f)

[1 2 3]
[1 2 3]
######
[1 2 3]
[100   2   3]


# **Mathematics**

In [ ]:
g = np.array([1, 2, 3, 4])
print(g)

[1 2 3 4]


In [ ]:
g+2

array([3, 4, 5, 6])

In [ ]:
g-2

array([-1,  0,  1,  2])

In [ ]:
g/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
g*2

array([2, 4, 6, 8])

In [ ]:
h = np.array([1, 0, 1, 0])
print(h)

[1 0 1 0]


In [ ]:
g+h

array([2, 2, 4, 4])

In [ ]:
g**2

array([ 1,  4,  9, 16])

In [ ]:
np.sin(g)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(h)

array([0.54030231, 1.        , 0.54030231, 1.        ])

# **Linear Algebra**

In [ ]:
i = np.ones((2, 3))
print(i)
j = np.full((3, 2), 2)
print(j)

np.matmul(i, j)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#k l m n o p q

# find the determinant
k = np.identity(3)
np.linalg.det(k)

1.0

# **Statistics**

In [ ]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [ ]:
np.max(stats, axis = 0)

6

In [ ]:
np.sum(stats, axis = 1)

array([ 6, 15])

# **Reorganizing Arrays**

In [ ]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print(before.shape)

after = before.reshape((8, 1))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
# Vertical Stacking
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
v3 = np.vstack([v1, v2, v2, v2, v1])
print(v3)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [ ]:
# Horizontal Stacking
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
h3 = np.hstack((h1, h2))
print(h3)

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


# **Miscellaneous**

**Load data from file**

In [ ]:
file_data = np.genfromtxt('data.txt', delimiter=',', dtype=np.int32)
print(file_data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# **Boolean Masking and Advanced Indexing**

In [ ]:
file_data >= 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
file_data[file_data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
#index with a list

l = np.array([1,2,3,4,5,6,7,8,9])
l[[1,2,8]]

array([2, 3, 9])

In [ ]:
print(np.any(file_data > 50, axis=0))
print('######')
print(np.all(file_data > 50, axis=0))

[False False False False  True  True False  True  True False False False
 False False False False  True  True]
######
[False False False False  True False False False False False False False
 False False False False False False]


In [ ]:
(file_data > 50) & (file_data < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
~((file_data > 50) & (file_data < 100))
# ~ >> means not (the inverse)

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
m = np.array(range(30)) + 1
m = m.reshape((6, 5))
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
m[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [ ]:
m[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [ ]:
m[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])